# Generated by Django 5.2.10 on 2026-01-18 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Company')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('other', models.JSONField(blank=True, help_text='Additional contact information (e.g., WhatsApp, VK, position)', null=True, verbose_name='Other contacts')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Urgency')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due date')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('canceled', 'Canceled')], default='todo', max_length=20, verbose_name='Status')),
                ('contact_freeform', models.CharField(blank=True, help_text='Manual contact info (if not using contact book)', max_length=500, verbose_name='Freeform contact')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('contact', models.ForeignKey(blank=True, help_text='Reference to contact from your contact book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='planner.contact', verbose_name='Contact')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='File')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Original filename')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='File size (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='planner.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['owner', '-created_at'], name='planner_con_owner_i_195f02_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'status', '-created_at'], name='planner_tas_owner_i_6224a2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'urgency'], name='planner_tas_owner_i_1115a4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'due_date'], name='planner_tas_owner_i_53b5e1_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['owner', 'task'], name='planner_att_owner_i_a00fa9_idx'),
        ),
    ]
