# Generated by Django 5.2.10 on 2026-01-20 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tagged_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Tagged user'),
        ),
        migrations.AddField(
            model_name='task',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Total tracked time for the task in seconds', verbose_name='Time spent (seconds)'),
        ),
        migrations.AddField(
            model_name='task',
            name='tracking_completed',
            field=models.BooleanField(default=False, help_text='Whether the time tracking session is завершен', verbose_name='Tracking completed'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('links', models.JSONField(blank=True, help_text='List of project links (label + url)', null=True, verbose_name='Links')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='planner.project', verbose_name='Project'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', '-created_at'], name='planner_pro_owner_i_682e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'name'], name='planner_pro_owner_i_2377f8_idx'),
        ),
    ]
