# Generated by Django 5.2.10 on 2026-01-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_task_tagged_user_task_time_spent_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pomodoro_sessions',
            field=models.PositiveIntegerField(default=0, help_text='Number of completed pomodoro focus sessions', verbose_name='Pomodoro sessions'),
        ),
    ]
