# Generated by ChatGPT on 2025-09-05
import uuid

from django.db import migrations, models


def populate_link_tokens(apps, schema_editor):
    Profile = apps.get_model('planner', 'Profile')
    for profile in Profile.objects.all():
        profile.telegram_link_token = uuid.uuid4()
        profile.save(update_fields=['telegram_link_token'])


class Migration(migrations.Migration):
    dependencies = [
        ('planner', '0006_contact_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.BigIntegerField(
                blank=True,
                null=True,
                verbose_name='Telegram chat ID',
                help_text='Linked Telegram chat identifier.',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_link_token',
            field=models.UUIDField(
                editable=False,
                null=True,
                verbose_name='Telegram link token',
            ),
            preserve_default=False,
        ),
        migrations.RunPython(populate_link_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='telegram_link_token',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name='Telegram link token',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_linked_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Telegram linked at',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_notifications_enabled',
            field=models.BooleanField(
                default=True,
                verbose_name='Telegram notifications enabled',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_notify_on_tag',
            field=models.BooleanField(
                default=True,
                verbose_name='Notify on tag in Telegram',
            ),
        ),
    ]
