# Generated by Django 5.2.10 on 2026-01-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0007_profile_telegram_bot_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAnalyticsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                (
                    "yandex_metrika_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Numeric counter identifier from Yandex.Metrika.",
                        null=True,
                        verbose_name="Yandex.Metrika counter ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Toggle to enable or disable analytics scripts globally.",
                        verbose_name="Analytics enabled",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "Site analytics settings",
                "verbose_name_plural": "Site analytics settings",
            },
        ),
    ]
