# Generated by Codex on 2026-01-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('planner', '0007_profile_telegram_bot_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'head_html',
                    models.TextField(
                        blank=True,
                        help_text='HTML snippets that will be injected into the <head> tag.',
                        verbose_name='Head HTML',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Updated at'),
                ),
            ],
            options={
                'verbose_name': 'Site setting',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
