# Generated by Django 5.2.10 on 2026-01-25 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_sitesetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked at')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share', to='planner.contact', verbose_name='Contact')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_shares', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Contact Share',
                'verbose_name_plural': 'Contact Shares',
                'indexes': [models.Index(fields=['token'], name='planner_con_token_af41ad_idx'), models.Index(fields=['owner', '-created_at'], name='planner_con_owner_i_266b78_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_shares', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share', to='planner.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Share',
                'verbose_name_plural': 'Project Shares',
                'indexes': [models.Index(fields=['token'], name='planner_pro_token_98f5f2_idx'), models.Index(fields=['owner', '-created_at'], name='planner_pro_owner_i_5c613f_idx')],
            },
        ),
    ]
