# Generated by Django 5.2.10 on 2026-01-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0008_siteanalyticssettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="yandex_metrika_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="Personal counter identifier used by the frontend.",
                null=True,
                verbose_name="Yandex.Metrika counter ID",
            ),
        ),
    ]
