# Generated by Django 5.2.10 on 2026-01-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_profile_self_contact_profile_share_invite_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contact_freeform_list',
            field=models.JSONField(blank=True, help_text='Manual contact info list (if not using contact book)', null=True, verbose_name='Freeform contacts'),
        ),
        migrations.AddField(
            model_name='task',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='tasks_multi', to='planner.contact', verbose_name='Contacts'),
        ),
    ]
