# Generated by Django 5.2.10 on 2026-01-31 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_task_status_defaults_ru'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='planner_tas_owner_i_9d08e2_idx',
            old_name='planner_tas_owner_i_6224a2_idx',
        ),
    ]
